### ISSUE TITLE
Not compatible with mtl-2.3.1/transformers-0.6

### ISSUE THREAD

**Issue by ysangkok** [Gabriella439/Haskell-Pipes-Safe-Library#55]
Hi, thanks for the Pipes library.

Trying to update the dependencies of Servant to get ready for the fixed mtl-2.3.1, and I noticed that pipes-safe isn't compatible.

Given that GHC probably isn't going to ship this any time soon, there is no rush to upgrading. But since I didn't see an issue, I thought I'd create one.

Cheers.

**Comment by Gabriella439** [comment]
This was fixed by https://github.com/Gabriella439/Haskell-Pipes-Safe-Library/pull/56

I also published the matching revision to Hackage so I think you should be good to go now

**Comment by ysangkok** [comment]
Thanks for the revision! It isn't sufficient though, since [only mtl was changed, but not transformers](https://hackage.haskell.org/package/pipes-safe-2.3.4/revisions/). ghc-9.6.1 ships transformers-0.6, and that series is still excluded.

The linked PR doesn't bump the transformers bound. That still makes sense, because while transformers-0.6 implies using mtl-2.3, the reverse is not the case. E.g. mtl-2.3 still works with transformers-0.5.

GHC-9.6 does ship transformers-0.6, so it would be nice to allow this series.
