### ISSUE TITLE
primitive-0.8 not allowed

### ISSUE THREAD

**Issue by ysangkok** [Gabriella439/Haskell-Pipes-Safe-Library#60]
This is one of the last packages missing on:

* https://github.com/commercialhaskell/stackage/issues/6887

**Comment by Gabriella439** [comment]
oh, i didn't see it in the list

**Comment by ysangkok** [comment]
It probably wasn't listed because it was a disabled package when the list was made. I just re-enabled it two weeks ago: https://github.com/commercialhaskell/stackage/commit/30ebc6a31f7acb8eed02a539fd39e2f2768eeddb
